### ISSUE TITLE
Document Admin user for SonarCloud

### ISSUE THREAD

**Issue by Flurb** [com-pas/compas-architecture#100]
As an engineer
I want to know how I can get admin rights for SonarCloud
So I can set up SonarCloud checks for repositories myself.

Answer: you can be admin by asking a sonarcloud admin

Suggestion to discuss with @jmertic : Give @jmertic admin rights, give CoMPAS TSC members admin rights on Sonarcloud and remove the CoMPAS-general. And generate token on with one of the TSC members.

Document the way of working in contributing.md including the location of the password vault.

**Comment by Sander3003** [comment]
We need to document in the contributing.md the password manager of LF energy to acces the services and add the SonarCloud account via @jmertic

**Comment by jmertic** [comment]
I would just suggest creating a generic account that corresponds to a forward email to the TSC chairperson or something like that, and then we can add the credentials into the LFE 1Password vault.

**Comment by Sander3003** [comment]
@jmertic most account require 2FA today, this is a downside of a generic account

**Comment by jmertic** [comment]
We can save 2FA auth codes in 1Password, if that would help.

**Comment by dlabordus** [comment]
How to configure the projects and GitHub Actions is described [here](https://com-pas.github.io/contributing/GITHUB_ACTIONS.html#sonarcloud)

Existing users can be added as Admin, they need to login using GitHub Once.
And a existing user can then give that user Admin rights.
