### ISSUE TITLE
Add missing repositories to LFX Security Tool

### ISSUE THREAD

**Issue by Flurb** [com-pas/compas-architecture#125]
As an engineer
I want to add the SCL-dataservice and the openscd repositories to the LFX Security Tool
So I know when I'm using bad dependencies

https://security.lfx.linuxfoundation.org/#/

**Comment by Sander3003** [comment]
@Flurb can you add the form?

**Comment by Flurb** [comment]
https://jira.linuxfoundation.org/plugins/servlet/theme/portal/4/group/100, then click "Get Help with LFX Security".
