### ISSUE TITLE
1 example of publish a Docker image(s) of CoMPAS

### ISSUE THREAD

**Issue by Sander3003** [com-pas/compas-architecture#126]
**As** an system admin
**I would like** to be able to download the CoMPAS containers form the open source community
**So** I can deploy CoMPAS easy within my own environment

**Background**
To get tracktion with the CoMPAS community it is important to lower the barrier to use CoMPAS. Therefore is would be nice if we can provide containers 

**Acceptance criteria**
1 micro service is downloadable for end-users

**Comment by Sander3003** [comment]
This is now possible: https://hub.docker.com/orgs/lfenergycompas/repositories
@Flurb correct?

**Comment by Flurb** [comment]
Done, multiple services can be downloaded via Docker Hub:

https://hub.docker.com/r/lfenergycompas/compas-scl-data-service
https://hub.docker.com/r/lfenergycompas/compas-open-scd
