### ISSUE TITLE
Dependabot Pull Request and GitHub Actions

### ISSUE THREAD

**Issue by dlabordus** [com-pas/compas-architecture#134]
As a developer
I want all Github action to run normally
S that I don't have to restart them manually.

Background:
When Dependabot creates a Pull Request the GitHub Action are also executed, but as a Bot.
A Bot can't access Secrets anymore. So some actions fail because of missing secrets, like the SonarCloud and AutomateProjects.
Maybe the Build will also fail in some time, because of GitHub Packages, but now the cache seems to solve this.

There are some solutions, but i doubt if these not again cause security issues.
https://github.com/dependabot/dependabot-core/issues/3253
https://securitylab.github.com/research/github-actions-preventing-pwn-requests/

**Comment by randy993** [comment]
@dlabordus Is this still an issue?

**Comment by dlabordus** [comment]
> @dlabordus Is this still an issue?

Yes

**Comment by dlabordus** [comment]
Most issues have been resolved by @Flurb by rewriting the GitHub Actions.

But there is still one issue with the GitHub Action "Add issues and pull request to project boards". 
Pull requests aren't added to the general project board, because that action won't run on type "pull_request_target".
This is a issue of that specific action we use, but maybe see how we can solve that.
Is would be nice to have a overview on all repositories? Makes keeping track of the Pull Request much easier.

**Comment by dlabordus** [comment]
Maybe see if we can replace the project boards action with something like found [here](https://docs.github.com/en/issues/planning-and-tracking-with-projects/automating-your-project/automating-projects-using-actions)
