### ISSUE TITLE
What is the purpose of using the Signoff flag?

### ISSUE THREAD

**Issue by Flurb** [com-pas/compas-architecture#15]
I was wondering why we are using the signoff flag for our commits :)

**Comment by FredFousPro** [comment]
It is an imposition of the technical charter (https://github.com/com-pas/contributing/blob/master/CoMPAS%20Technical%20Charter%207-6-2020.pdf) of the project § 7.1.ii :

ii. All new inbound code contributions must also be accompanied by a
Developer Certificate of Origin (http://developercertificate.org) sign-off in
the source code system that is submitted through a TSC-approved
contribution process which will bind the authorized contributor and, if not
self-employed, their employer to the applicable license;

**Comment by FredFousPro** [comment]
sorry § 7.b.ii
