### ISSUE TITLE
Live demo environment for LF energy CoMPAS

### ISSUE THREAD

**Issue by Sander3003** [com-pas/compas-architecture#152]
As a potential user
I want to try CoMPAS in a live demo environment
So I can try CoMPAS with just a browser and have a hard time to hassle with internal security policies and procedures just for testing.

Background
A lot of companies have strict security policies to install software. In case of CoMPAS today the need to install docker, have acces to dockerhub etc. To lower the barrier for adoption, it would be nice if their is just a public server that runs CoMPAS for testing purpose.

Idea's:
Wipe the database every day
Use the LF account to log-in into the demo environment (to prevent abuse)
URL idea: https://demo.compas.energy

**Comment by dlabordus** [comment]
See issues 
- https://github.com/com-pas/compas-architecture/issues/167
- https://github.com/com-pas/compas-architecture/issues/169
- https://github.com/com-pas/compas-architecture/issues/168

**Comment by Sander3003** [comment]
Live demo is live!
