### ISSUE TITLE
Comments on Python

### ISSUE THREAD

**Issue by keith-gray-powereng** [com-pas/compas-architecture#16]
I see some of the comments regarding Python in the table. I wanted to suggest maybe taking another look at it.

1. The flask web framework is an extremely popular library in Python. Development has not stalled. The three main Python web frameworks are flask, django, and pyramid.
2. I may be confused but one of the comments appears to indicate that Python has no standard library. This is not true, Python is known for its "batteries included" philosophy. Additionally, it has thousands of libraries easily installed from the python package index, [pypi.org](https://pypi.org/).

**Comment by Flurb** [comment]
Good one! That is something we need to keep in mind during discussions in the future 👍

**Comment by Flurb** [comment]
Closed because we have chosen to use Java and Java frameworks
