### ISSUE TITLE
Create AWS CoMPAS demo environment architecture

### ISSUE THREAD

**Issue by Sander3003** [com-pas/compas-architecture#167]
Create an architecture to run CoMPAS on AWS for demo purposes and define the next steps.

Todo:
- [x] Link AWS account to LF energy
- [x] Create issues for the next steps

**Acceptance criteria**
URL: demo.compas.energy
(if possible/needed): Login with your LF account
To test: https://auth0.com/

Start with an AWS SSO/internal identity provider (and switch later)

Every one that logs in get admin access (full read/write)

Use https (via Let's encrypt)

Contact @jmertic to get an URL redirects / DNS changes etc

No nsdoc files hosted on the demo instance

Ask @dlabordus for insights into the current (non public) setup

Automate deployment (including description)

**Comment by Sander3003** [comment]
New stories:
AWS SSO
Load balancer
Deployment of containers
LF energy SSO

**Comment by pascalwilbrink** [comment]
Created seperated issues
