### ISSUE TITLE
Add Cognito to loadbalancer

### ISSUE THREAD

**Issue by pascalwilbrink** [com-pas/compas-architecture#168]
The CoMPAS demo environment needs an authorized user to prevent abuse. 
For this we can use Cognito from AWS as an IAM.

Todo:
- [x] Add https listener to loadbalancer
- [x] Add SSL certificate to ACM
- [x] Create a userpool in Cognito
- [x] Create internal Cognito users
- [x] Add Cognito to Loadbalancer
- [x] Document solution

**Investigation**
- Connect to Auth0/ LF Energy SSO
- Add users/admins to AWS organisation

**Comment by Sander3003** [comment]
https://github.com/com-pas/compas-architecture/issues/167

**Comment by Sander3003** [comment]
What is missing to finish this story?

**Comment by Sander3003** [comment]
@pascalwilbrink can this issue be closed?
