### ISSUE TITLE
Host CoMPAS containers on AWS

### ISSUE THREAD

**Issue by pascalwilbrink** [com-pas/compas-architecture#169]
For a demo environment of CoMPAS, we want to host the CoMPAS containers on AWS.

Todo:
- [x] Host CoMPAS containers on ECS/AWS
- [x] Host Postgres Database on ECS/AWS
- [x] Test Database Connection
- [x] Create Loadbalancer / ALB
- [x] Investigate cloudformation for connection between ALB and specified Docker containers
- [x] Document setup (can be part of the deployment https://github.com/com-pas/compas-deployment)

**Investigation**
- Investigate how to maintain the docker containers (latest version)
- Check on how many instances should be run/ replicas (SCL Validator)
- Investigate cloudformation (Infrastructure as code)

**Comment by Sander3003** [comment]
https://github.com/com-pas/compas-architecture/issues/167

**Comment by Sander3003** [comment]
It already works: https://demo.compas.energy/

@pascalwilbrink What is currently missing from this story?
