### ISSUE TITLE
Logon with LF id on demo.compas.energy

### ISSUE THREAD

**Issue by Sander3003** [com-pas/compas-architecture#171]
Connect demo.compas.energy with the LF ID for logon.

Todo:
[ ] LF energy should create an auth0 application (apply for one)

Acceptance criteria:
Login with your LF id into demo.compas.energy

**Comment by Sander3003** [comment]
Steps:
- Fix the AWS root name issue first
- Update the ARN in the json files
- Redeploy/create a new load balancer
- Update the Cname for demo.compas.energy
- Create auth0 with the application

**Comment by Sander3003** [comment]
We are waiting for LF energy to reply.

**Comment by Sander3003** [comment]
Can be done after de migration from @pascalwilbrink space to LF energy CoMPAS space in AWS.

**Comment by Sander3003** [comment]
@juancho0202 will take a look at it

**Comment by pascalwilbrink** [comment]
Settings


Allowed callback urls:
https://compas-energy.auth.eu-west-1.amazoncognito.com, 
https://compas-energy.auth.eu-west-1.amazoncognito.com/oauth2/idpresponse
https://demo.compas.energy/oauth2/idpresponse

Application type: SPA
Allow Cross-Origin Authentication: True


What we need:
	=> Advanced Settings => Endpoints 
		=>
			OAuth Authorization URL
			OAuth Token URL
			JSON web Key Set

**Comment by pascalwilbrink** [comment]
Fixed,
see

https://demo.compas.energy
