### ISSUE TITLE
Migrate AWS to new LFEnergy root account

### ISSUE THREAD

**Issue by Sander3003** [com-pas/compas-architecture#180]
Since we have a new Root Account for AWS from LFEnergy, we need to migrate the AWS services to this new root account.

This includes:

- ECS migration
- Load balancer Migration + HTTPS + point demo.compas.energy to this loadbalancer
- Check that Github Actions still work
- Auth0 Migration
- Update documentation (taks definitions)
- Document manual steps  that are not described in deployment documentation: https://github.com/com-pas/compas-deployment/tree/main/aws
- Export "old" AWS environment

 

Once everything works, we can/need to change the Auth0 migration to the LFEnergy Auth0 instance.

**Comment by Sander3003** [comment]
It is unclear where the what the open tickets are at the LF energy servicedesk.

**Comment by Sander3003** [comment]
It oder to swith more easy: use 2 browers (e.g. 1 in private mode); deployment take sometimes multiple minutes

**Comment by juancho0202** [comment]
Currently we are missing a fix in the redirect after auth0 login and an upgrade of the compas-open-scd version, but demo.compas.energy is successfully moved to the LFEnergy AWS account. #171 will fix this.
