### ISSUE TITLE
How do we release our application?

### ISSUE THREAD

**Issue by Flurb** [com-pas/compas-architecture#23]
As a deployer
I would like to know how we release our CoMPAS application
So I'm able to deploy the CoMPAS application

Background
OpenSCD-CoMPAS has already a release process in place.

Use the release function of Github
Based on a new release: 
- Set version (maven)
- Publish artifacts on Github packages 
- (Optional) Build docker image and publish to dockerhub

Idea: set the current version on local-snapshot, this version can be used locally.
This way we can set the version passed from the release process, see compas-openscd.

**Comment by Sander3003** [comment]
Their is already release proces in place for CoMPAS-openSCD.
