### ISSUE TITLE
The link to CoMPAS Technical Steering Committee on wiki doesn't work

### ISSUE THREAD

**Issue by Jonasvdbo** [com-pas/compas-architecture#33]
Hi,

I would like to let you know that the link to the CoMPAS Technical Steering Committee on https://wiki.lfenergy.org/display/HOME/CoMPAS doesn't work.

Best regards,
Jonas

**Comment by Sander3003** [comment]
Hi @Jonasvdbo, 

Thanks for the bug report. The issue is now solved.
