### ISSUE TITLE
In document TECHNOLOGY_CHOICES.md, line 110, possible typo

### ISSUE THREAD

**Issue by joyshmitz** [com-pas/compas-architecture#56]
DI-EMCS-81850 Technical Report For MIL-STD-3023 Hardness Allocation, maybe you meant "IEC 61850/IEC CIM configuration files...

search gave result for 81850 https://webstore.ansi.org/Search/Find?in=1&st=DI-EMCS-81850

**Comment by Sander3003** [comment]
Hi @joyshmitz, Thanks for your bug report. I did send a pull request to fix the issue. What is your impression of the technical choices for the CoMPAS project?

**Comment by joyshmitz** [comment]
Hi @Sander3003 , I see a lot of fundamental work on building an understandable and modern system of energy control and management

**Comment by Sander3003** [comment]
This looks fixed
