### ISSUE TITLE
Deprecated rules in SonarCloud should be removed

### ISSUE THREAD

**Issue by Flurb** [com-pas/compas-architecture#58]
As a developer
I want to remove the deprecated SonarCloud rules
So we don't get deprecated warnings/errors.

Acceptance criteria:
- Find out how we can remove them (maybe deleting, maybe inactivating, changing SonarCloud profile, find out the best way)
- Do it.

**Comment by Sander3003** [comment]
@Flurb what is the status?

**Comment by dlabordus** [comment]
Look like we already solve this problem. SonarCloud isn't complaining anymore about deprecated rules.
