### ISSUE TITLE
Limit the default view of SonarCloud 

### ISSUE THREAD

**Issue by Flurb** [com-pas/compas-architecture#59]
By default, the view of SonarCloud seems a bit "too public".
Things like number of bugs and vulnerabilities are viewable without having an account for example. This is a bad practice.

It's fine to show some information (like an overall score), because it's still an open source project.
But showing specific vulnerabilities is perhaps not the best idea :)

**Comment by Sander3003** [comment]
On the other hand, this could lead to fixing the issues.

**Comment by Flurb** [comment]
After thinking even more:

In theory it's of course possible someone can checkout the code and let is scan by some other SonarCloud (or other tool) instance.

**Comment by Flurb** [comment]
And maybe people are getting suspicious when we say: We are running SonarCloud to scan the code, but we aren't making it public".

**Comment by Flurb** [comment]
Closed because it's an Open Source project and this is fine (being this public)
