### ISSUE TITLE
broken link on wiki site page CoMPAS Architecture 

### ISSUE THREAD

**Issue by joyshmitz** [com-pas/compas-architecture#77]
at [CoMPAS Architecture](https://wiki.lfenergy.org/display/HOME/CoMPAS+Architecture)
the picture is not presented and the link works in the section [Technical Architecture Overview](https://github.com/com-pas/compas-architecture/blob/master/technical-overview/CoMPAS_technical_architecture_overview.svg)

[apparently the file was moved to the repository, it is probably him](https://github.com/com-pas/compas-architecture/blob/master/images/CoMPAS_technical_architecture_overview.svg)

**Comment by Flurb** [comment]
Thanks!
When #78 is merged, the link can be updated!

**Comment by Flurb** [comment]
Fixed! Thanks @joyshmitz !
