### ISSUE TITLE
Add overview of Github actions to the documentation

### ISSUE THREAD

**Issue by Sander3003** [com-pas/compas-architecture#84]
As a CoMPAS developer

I want to know how Sonar cloud Github Action are setup and an overview of the Github Actions use

So I can re-use this knowledge for other part of the CoMPAS project

Acceptance criteria:

Documentation on the CoMPAS architecture page

Draft text:

Adding new SonarCloud project

For your Github Organization of the repository that needs to be analyzed, go to your organization settings in Github.Installed Github Apps -> SonarCloud -> Repository Access -> Select the repo to be added (or do all repositories if you want SonarCloud to have access to all repositories)

Create new project at:https://sonarcloud.io/projects/create

Select the repository to be analyzed, click Set Up.(Next steps are also described in the SonarCloud app)

Choose Analysis Method: With Github Actions

Create the SONAR_TOKEN secret in your repo to analyze with the given secret:Go to the repository -> Settings - Secrets -> New repository secret -> Insert name & secret value

In repository:Create .github/workflows/sonarcloud-analysis.yml

name: SonarCloud Analysis

on: push

jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

Add sonar-project.properties file

sonar.projectKey=<key>
sonar.organization=<organization>

Commit/Push everything and let it run!

**Comment by syllamoh** [comment]
Hi @Sander3003 
The GitHub Action script is not a template that works every where, specially build action. 
One should know what to build before writing the script. There's what we call cross repository build and trivial build GitHub action will not work for that.
An extra sonar properties file can be replaced in the the build command.

**Comment by Flurb** [comment]
Closed because documentation has been added.
By using Github Packages, it's relatively easy to make projects dependent on each other.
