### ISSUE TITLE
How can we identify the SCL? Add private type/name/UUID (SCL type)

### ISSUE THREAD

**Issue by Sander3003** [com-pas/compas-architecture#86]
As End-user

I like to define the different SCL types/filename/UUID

So I can see select/query on the different SCL file types.

Background:

See NEN Connect - IEC 61850-6 for inspiration or ask the question on slack. 8.3.6 describes how to add private elements

 

Acceptance criteria:

- Decision on approach (inside the XML)
- Document the decision on the architecture
- Check on slack if other already made these extensions (OSMOSE)

**Comment by Sander3003** [comment]
Suggested solution (to be checked by the standard):

header.id will be the UUID

Add a compass namespace and add these private elements:

Add private element before the header (if possible)
Filename: <Default filename>
SCCtype: <SCD/ICD/SSD/etc>

**Comment by Sander3003** [comment]
Relates to: https://github.com/com-pas/compas-scl-data-service/issues/12

**Comment by Sander3003** [comment]
Build a private extension to add the SCL file inside the XML files.

**Comment by Sander3003** [comment]
Slack question: https://lfenergy.slack.com/archives/C01926K9D39/p1620825917091100

**Comment by Flurb** [comment]
Linked issue: #105

**Comment by Sander3003** [comment]
@Flurb is this done?

**Comment by Flurb** [comment]
This is done. @Sander3003
