### ISSUE TITLE
Overview of the Github issues

### ISSUE THREAD

**Issue by Sander3003** [com-pas/compas-architecture#89]
As a developer
I want to know and setup a overview of Github issues in the organisation and issue maintainance
So I manage the issues over the multiple projects

Background:
Their is a lack of overview of issues and the overview of the management

Acceptance criteria:

- Documentation of the workflow
- Github settings kanban board settings right
- Select a repro for general issues

**Comment by Sander3003** [comment]
My idea is to use github actions to automaticly assign issues to the CoMPAS overview project. Maybe this could be usefull: https://github.com/marketplace/actions/automate-projects

**Comment by Flurb** [comment]
Added to organization project board.
