### ISSUE TITLE
Add edit on github to the pages

### ISSUE THREAD

**Issue by Sander3003** [com-pas/compas-architecture#9]
Example: https://docs.linuxfoundation.org/docs/
![image](https://user-images.githubusercontent.com/7427358/91724366-827f6000-eb9d-11ea-9620-5acc5126a1d2.png)

This lowers the barrier for people to add/edit documentation.

**Comment by Sander3003** [comment]
@Flurb is looks fixed right?

**Comment by Flurb** [comment]
Fixed
